<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <AssemblyName>SciLorsMashedTrainer</AssemblyName>
    <RootNamespace>SciLors_Mashed_Trainer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests/**" />
    <Compile Remove="tools/**" />
    <None Remove="tests/**" />
    <None Remove="tools/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.3" />
    <PackageReference Include="Avalonia.Svg.Skia" Version="11.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Asm\*.bin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Asm\*.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <AvaloniaResource Include="Img\packs\**\*.png" />
  </ItemGroup>
</Project>

